server {
    listen 80;
    server_name nginx2;

    include /etc/nginx/snippets/trusted_xff.conf;

    location = / {
        include /etc/nginx/snippets/proxy_common.conf;
        proxy_pass http://app:8080/;
    }

    location /via/app/ {
        include /etc/nginx/snippets/proxy_common.conf;
        proxy_pass http://app:8080/;
    }

    location /via/nginx3/ {
        include /etc/nginx/snippets/proxy_common.conf;
        proxy_pass http://nginx3/via/app/;
    }

    location /via/nginx1/ {
        include /etc/nginx/snippets/proxy_common.conf;
        proxy_pass http://nginx1/;
    }
}
